# Generated by Django 5.0.7 on 2024-08-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstox_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstoxtoken',
            name='refresh_token',
        ),
    ]
