# Generated by Django 5.0.7 on 2024-10-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstox_integration', '0008_profile_experience_profile_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_sectors',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trading_knowledge',
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
