# Generated by Django 5.0.7 on 2024-10-27 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('upstox_integration', '0010_remove_profile_experience_profile_experience_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpstoxToken',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='upstox_customuser_set', related_query_name='upstox_customuser', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='upstox_customuser_set', related_query_name='upstox_customuser', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upstox_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
