# Generated by Django 5.0.7 on 2024-10-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstox_integration', '0012_upstoxtoken_remove_profile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trading_knowledge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
