# Generated by Django 5.0.7 on 2024-11-01 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstox_integration', '0015_rename_timestamp_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='average_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'stock_symbol')},
        ),
    ]
